[build-system]
requires = [
    "setuptools",
    "setuptools-scm",
]

build-backend = "setuptools.build_meta"

[project]
name = "bridger"
dynamic = ["version"]
description = "A bridge between MQTT and Postgres for Meshtastic mesh network visualization"
readme = "README.md"

authors = [
    { name="Andy Shinn", email="andys@andyshinn.as" },
]

dependencies = [
    "cryptography",
    "dataclasses-json",
    "loguru",
    "meshtastic",
    "paho-mqtt",
    "protobuf",
    "psycopg2-binary",
    "python-dotenv",
    "sqlalchemy",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "requests-mock",
]

[project.urls]
Source = "https://github.com/ntxmesh/bridger"
Graphs = "https://graphs.ntxmesh.net"

[tool.black]
line-length = 125

[tool.isort]
profile = "black"
line_length = 125

[tool.setuptools]
py-modules = []

[tool.pytest.ini_options]
consider_namespace_packages = true
addopts = [
    "--cov=bridger",
    "--cov-report=term-missing",
]
